//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication1.ServiceReference1.HelloWorldResponse HelloWorld(WebApplication1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplication1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/conectarServidor", ReplyAction="*")]
        bool conectarServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/conectarServidor", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> conectarServidorAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Tabla del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registrar", ReplyAction="*")]
        WebApplication1.ServiceReference1.RegistrarResponse Registrar(WebApplication1.ServiceReference1.RegistrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.RegistrarResponse> RegistrarAsync(WebApplication1.ServiceReference1.RegistrarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarUsuario", ReplyAction="*")]
        WebApplication1.ServiceReference1.VerificarUsuarioResponse VerificarUsuario(WebApplication1.ServiceReference1.VerificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VerificarUsuarioResponse> VerificarUsuarioAsync(WebApplication1.ServiceReference1.VerificarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Contraseña del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarEmpleadoOAdministrador", ReplyAction="*")]
        WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorResponse VerificarEmpleadoOAdministrador(WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarEmpleadoOAdministrador", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorResponse> VerificarEmpleadoOAdministradorAsync(WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registrar", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.RegistrarRequestBody Body;
        
        public RegistrarRequest() {
        }
        
        public RegistrarRequest(WebApplication1.ServiceReference1.RegistrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tabla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Campos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Valores;
        
        public RegistrarRequestBody() {
        }
        
        public RegistrarRequestBody(string Tabla, string Campos, string Valores) {
            this.Tabla = Tabla;
            this.Campos = Campos;
            this.Valores = Valores;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.RegistrarResponseBody Body;
        
        public RegistrarResponse() {
        }
        
        public RegistrarResponse(WebApplication1.ServiceReference1.RegistrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrarResult;
        
        public RegistrarResponseBody() {
        }
        
        public RegistrarResponseBody(bool RegistrarResult) {
            this.RegistrarResult = RegistrarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.VerificarUsuarioRequestBody Body;
        
        public VerificarUsuarioRequest() {
        }
        
        public VerificarUsuarioRequest(WebApplication1.ServiceReference1.VerificarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contraseña;
        
        public VerificarUsuarioRequestBody() {
        }
        
        public VerificarUsuarioRequestBody(string Usuario, string Contraseña) {
            this.Usuario = Usuario;
            this.Contraseña = Contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.VerificarUsuarioResponseBody Body;
        
        public VerificarUsuarioResponse() {
        }
        
        public VerificarUsuarioResponse(WebApplication1.ServiceReference1.VerificarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VerificarUsuarioResult;
        
        public VerificarUsuarioResponseBody() {
        }
        
        public VerificarUsuarioResponseBody(int VerificarUsuarioResult) {
            this.VerificarUsuarioResult = VerificarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarEmpleadoOAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarEmpleadoOAdministrador", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequestBody Body;
        
        public VerificarEmpleadoOAdministradorRequest() {
        }
        
        public VerificarEmpleadoOAdministradorRequest(WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarEmpleadoOAdministradorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codempleado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contraseña;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rol;
        
        public VerificarEmpleadoOAdministradorRequestBody() {
        }
        
        public VerificarEmpleadoOAdministradorRequestBody(int codempleado, string Contraseña, string rol) {
            this.codempleado = codempleado;
            this.Contraseña = Contraseña;
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarEmpleadoOAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarEmpleadoOAdministradorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorResponseBody Body;
        
        public VerificarEmpleadoOAdministradorResponse() {
        }
        
        public VerificarEmpleadoOAdministradorResponse(WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarEmpleadoOAdministradorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VerificarEmpleadoOAdministradorResult;
        
        public VerificarEmpleadoOAdministradorResponseBody() {
        }
        
        public VerificarEmpleadoOAdministradorResponseBody(int VerificarEmpleadoOAdministradorResult) {
            this.VerificarEmpleadoOAdministradorResult = VerificarEmpleadoOAdministradorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.WebService1Soap>, WebApplication1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.HelloWorldResponse WebApplication1.ServiceReference1.WebService1Soap.HelloWorld(WebApplication1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication1.ServiceReference1.HelloWorldRequest inValue = new WebApplication1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication1.ServiceReference1.HelloWorldRequestBody();
            WebApplication1.ServiceReference1.HelloWorldResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.HelloWorldResponse> WebApplication1.ServiceReference1.WebService1Soap.HelloWorldAsync(WebApplication1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplication1.ServiceReference1.HelloWorldRequest inValue = new WebApplication1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication1.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplication1.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public bool conectarServidor() {
            return base.Channel.conectarServidor();
        }
        
        public System.Threading.Tasks.Task<bool> conectarServidorAsync() {
            return base.Channel.conectarServidorAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.RegistrarResponse WebApplication1.ServiceReference1.WebService1Soap.Registrar(WebApplication1.ServiceReference1.RegistrarRequest request) {
            return base.Channel.Registrar(request);
        }
        
        public bool Registrar(string Tabla, string Campos, string Valores) {
            WebApplication1.ServiceReference1.RegistrarRequest inValue = new WebApplication1.ServiceReference1.RegistrarRequest();
            inValue.Body = new WebApplication1.ServiceReference1.RegistrarRequestBody();
            inValue.Body.Tabla = Tabla;
            inValue.Body.Campos = Campos;
            inValue.Body.Valores = Valores;
            WebApplication1.ServiceReference1.RegistrarResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).Registrar(inValue);
            return retVal.Body.RegistrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.RegistrarResponse> WebApplication1.ServiceReference1.WebService1Soap.RegistrarAsync(WebApplication1.ServiceReference1.RegistrarRequest request) {
            return base.Channel.RegistrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.RegistrarResponse> RegistrarAsync(string Tabla, string Campos, string Valores) {
            WebApplication1.ServiceReference1.RegistrarRequest inValue = new WebApplication1.ServiceReference1.RegistrarRequest();
            inValue.Body = new WebApplication1.ServiceReference1.RegistrarRequestBody();
            inValue.Body.Tabla = Tabla;
            inValue.Body.Campos = Campos;
            inValue.Body.Valores = Valores;
            return ((WebApplication1.ServiceReference1.WebService1Soap)(this)).RegistrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.VerificarUsuarioResponse WebApplication1.ServiceReference1.WebService1Soap.VerificarUsuario(WebApplication1.ServiceReference1.VerificarUsuarioRequest request) {
            return base.Channel.VerificarUsuario(request);
        }
        
        public int VerificarUsuario(string Usuario, string Contraseña) {
            WebApplication1.ServiceReference1.VerificarUsuarioRequest inValue = new WebApplication1.ServiceReference1.VerificarUsuarioRequest();
            inValue.Body = new WebApplication1.ServiceReference1.VerificarUsuarioRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contraseña = Contraseña;
            WebApplication1.ServiceReference1.VerificarUsuarioResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).VerificarUsuario(inValue);
            return retVal.Body.VerificarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VerificarUsuarioResponse> WebApplication1.ServiceReference1.WebService1Soap.VerificarUsuarioAsync(WebApplication1.ServiceReference1.VerificarUsuarioRequest request) {
            return base.Channel.VerificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VerificarUsuarioResponse> VerificarUsuarioAsync(string Usuario, string Contraseña) {
            WebApplication1.ServiceReference1.VerificarUsuarioRequest inValue = new WebApplication1.ServiceReference1.VerificarUsuarioRequest();
            inValue.Body = new WebApplication1.ServiceReference1.VerificarUsuarioRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contraseña = Contraseña;
            return ((WebApplication1.ServiceReference1.WebService1Soap)(this)).VerificarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorResponse WebApplication1.ServiceReference1.WebService1Soap.VerificarEmpleadoOAdministrador(WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequest request) {
            return base.Channel.VerificarEmpleadoOAdministrador(request);
        }
        
        public int VerificarEmpleadoOAdministrador(int codempleado, string Contraseña, string rol) {
            WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequest inValue = new WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequest();
            inValue.Body = new WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequestBody();
            inValue.Body.codempleado = codempleado;
            inValue.Body.Contraseña = Contraseña;
            inValue.Body.rol = rol;
            WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).VerificarEmpleadoOAdministrador(inValue);
            return retVal.Body.VerificarEmpleadoOAdministradorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorResponse> WebApplication1.ServiceReference1.WebService1Soap.VerificarEmpleadoOAdministradorAsync(WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequest request) {
            return base.Channel.VerificarEmpleadoOAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorResponse> VerificarEmpleadoOAdministradorAsync(int codempleado, string Contraseña, string rol) {
            WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequest inValue = new WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequest();
            inValue.Body = new WebApplication1.ServiceReference1.VerificarEmpleadoOAdministradorRequestBody();
            inValue.Body.codempleado = codempleado;
            inValue.Body.Contraseña = Contraseña;
            inValue.Body.rol = rol;
            return ((WebApplication1.ServiceReference1.WebService1Soap)(this)).VerificarEmpleadoOAdministradorAsync(inValue);
        }
    }
}
