//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/conectarServidor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool conectarServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/conectarServidor", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> conectarServidorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Registrar(string Tabla, string Campos, string Valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegistrarAsync(string Tabla, string Campos, string Valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int VerificarUsuario(string Usuario, string Contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> VerificarUsuarioAsync(string Usuario, string Contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarEmpleadoOAdministrador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int VerificarEmpleadoOAdministrador(int codempleado, string Contraseña, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarEmpleadoOAdministrador", ReplyAction="*")]
        System.Threading.Tasks.Task<int> VerificarEmpleadoOAdministradorAsync(int codempleado, string Contraseña, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagosiono", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Pagosiono(int CasillaInter, string pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagosiono", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> PagosionoAsync(int CasillaInter, string pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarcliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarcliente(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarcliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscarclienteAsync(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarCSVImpuesto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CargarCSVImpuesto(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarCSVImpuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CargarCSVImpuestoAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarCSVEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CargarCSVEmpleado(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarCSVEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CargarCSVEmpleadoAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarCSVPaquetes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CargarCSVPaquetes(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarCSVPaquetes", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CargarCSVPaquetesAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DespedirEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DespedirEmpleado(int CodEmpleado, string Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DespedirEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DespedirEmpleadoAsync(int CodEmpleado, string Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturaImagen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FacturaImagen(string UsuarioC, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturaImagen", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> FacturaImagenAsync(string UsuarioC, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarEstadoPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int VerificarEstadoPaquete(int codpaquete, int Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarEstadoPaquete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> VerificarEstadoPaqueteAsync(int codpaquete, int Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutorizarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AutorizarCliente(string UsuarioC, int link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutorizarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AutorizarClienteAsync(string UsuarioC, int link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EstadoPaquete(string NombrePaquete, string Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoPaquete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EstadoPaqueteAsync(string NombrePaquete, string Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarEstadopaqueteCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int VerificarEstadopaqueteCliente(string NombrePaquete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarEstadopaqueteCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<int> VerificarEstadopaqueteClienteAsync(string NombrePaquete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cambiodeestadopaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int cambiodeestadopaquete(string NombrePaquete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cambiodeestadopaquete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> cambiodeestadopaqueteAsync(string NombrePaquete);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.WebService1Soap>, WebApplication1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public bool conectarServidor() {
            return base.Channel.conectarServidor();
        }
        
        public System.Threading.Tasks.Task<bool> conectarServidorAsync() {
            return base.Channel.conectarServidorAsync();
        }
        
        public bool Registrar(string Tabla, string Campos, string Valores) {
            return base.Channel.Registrar(Tabla, Campos, Valores);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAsync(string Tabla, string Campos, string Valores) {
            return base.Channel.RegistrarAsync(Tabla, Campos, Valores);
        }
        
        public int VerificarUsuario(string Usuario, string Contraseña) {
            return base.Channel.VerificarUsuario(Usuario, Contraseña);
        }
        
        public System.Threading.Tasks.Task<int> VerificarUsuarioAsync(string Usuario, string Contraseña) {
            return base.Channel.VerificarUsuarioAsync(Usuario, Contraseña);
        }
        
        public int VerificarEmpleadoOAdministrador(int codempleado, string Contraseña, string rol) {
            return base.Channel.VerificarEmpleadoOAdministrador(codempleado, Contraseña, rol);
        }
        
        public System.Threading.Tasks.Task<int> VerificarEmpleadoOAdministradorAsync(int codempleado, string Contraseña, string rol) {
            return base.Channel.VerificarEmpleadoOAdministradorAsync(codempleado, Contraseña, rol);
        }
        
        public bool Pagosiono(int CasillaInter, string pago) {
            return base.Channel.Pagosiono(CasillaInter, pago);
        }
        
        public System.Threading.Tasks.Task<bool> PagosionoAsync(int CasillaInter, string pago) {
            return base.Channel.PagosionoAsync(CasillaInter, pago);
        }
        
        public System.Data.DataSet buscarcliente(string IDMask) {
            return base.Channel.buscarcliente(IDMask);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscarclienteAsync(string IDMask) {
            return base.Channel.buscarclienteAsync(IDMask);
        }
        
        public bool CargarCSVImpuesto(string path) {
            return base.Channel.CargarCSVImpuesto(path);
        }
        
        public System.Threading.Tasks.Task<bool> CargarCSVImpuestoAsync(string path) {
            return base.Channel.CargarCSVImpuestoAsync(path);
        }
        
        public bool CargarCSVEmpleado(string path) {
            return base.Channel.CargarCSVEmpleado(path);
        }
        
        public System.Threading.Tasks.Task<bool> CargarCSVEmpleadoAsync(string path) {
            return base.Channel.CargarCSVEmpleadoAsync(path);
        }
        
        public bool CargarCSVPaquetes(string path) {
            return base.Channel.CargarCSVPaquetes(path);
        }
        
        public System.Threading.Tasks.Task<bool> CargarCSVPaquetesAsync(string path) {
            return base.Channel.CargarCSVPaquetesAsync(path);
        }
        
        public bool DespedirEmpleado(int CodEmpleado, string Estado) {
            return base.Channel.DespedirEmpleado(CodEmpleado, Estado);
        }
        
        public System.Threading.Tasks.Task<bool> DespedirEmpleadoAsync(int CodEmpleado, string Estado) {
            return base.Channel.DespedirEmpleadoAsync(CodEmpleado, Estado);
        }
        
        public bool FacturaImagen(string UsuarioC, string link) {
            return base.Channel.FacturaImagen(UsuarioC, link);
        }
        
        public System.Threading.Tasks.Task<bool> FacturaImagenAsync(string UsuarioC, string link) {
            return base.Channel.FacturaImagenAsync(UsuarioC, link);
        }
        
        public int VerificarEstadoPaquete(int codpaquete, int Estado) {
            return base.Channel.VerificarEstadoPaquete(codpaquete, Estado);
        }
        
        public System.Threading.Tasks.Task<int> VerificarEstadoPaqueteAsync(int codpaquete, int Estado) {
            return base.Channel.VerificarEstadoPaqueteAsync(codpaquete, Estado);
        }
        
        public bool AutorizarCliente(string UsuarioC, int link) {
            return base.Channel.AutorizarCliente(UsuarioC, link);
        }
        
        public System.Threading.Tasks.Task<bool> AutorizarClienteAsync(string UsuarioC, int link) {
            return base.Channel.AutorizarClienteAsync(UsuarioC, link);
        }
        
        public bool EstadoPaquete(string NombrePaquete, string Estado) {
            return base.Channel.EstadoPaquete(NombrePaquete, Estado);
        }
        
        public System.Threading.Tasks.Task<bool> EstadoPaqueteAsync(string NombrePaquete, string Estado) {
            return base.Channel.EstadoPaqueteAsync(NombrePaquete, Estado);
        }
        
        public int VerificarEstadopaqueteCliente(string NombrePaquete) {
            return base.Channel.VerificarEstadopaqueteCliente(NombrePaquete);
        }
        
        public System.Threading.Tasks.Task<int> VerificarEstadopaqueteClienteAsync(string NombrePaquete) {
            return base.Channel.VerificarEstadopaqueteClienteAsync(NombrePaquete);
        }
        
        public int cambiodeestadopaquete(string NombrePaquete) {
            return base.Channel.cambiodeestadopaquete(NombrePaquete);
        }
        
        public System.Threading.Tasks.Task<int> cambiodeestadopaqueteAsync(string NombrePaquete) {
            return base.Channel.cambiodeestadopaqueteAsync(NombrePaquete);
        }
    }
}
