//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:1240/Service.asmx", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/conectarServidor", ReplyAction="*")]
        bool conectarServidor();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Tabla del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/Registrar", ReplyAction="*")]
        Practica1.ServiceReference1.RegistrarResponse Registrar(Practica1.ServiceReference1.RegistrarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDMask del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/BuscarLibro", ReplyAction="*")]
        Practica1.ServiceReference1.BuscarLibroResponse BuscarLibro(Practica1.ServiceReference1.BuscarLibroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDMask del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/BuscarLibroautor", ReplyAction="*")]
        Practica1.ServiceReference1.BuscarLibroautorResponse BuscarLibroautor(Practica1.ServiceReference1.BuscarLibroautorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FechahoyResult del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/Fechahoy", ReplyAction="*")]
        Practica1.ServiceReference1.FechahoyResponse Fechahoy(Practica1.ServiceReference1.FechahoyRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ordenarResult del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/ordenar", ReplyAction="*")]
        Practica1.ServiceReference1.ordenarResponse ordenar(Practica1.ServiceReference1.ordenarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codlibro del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/Prestamo", ReplyAction="*")]
        Practica1.ServiceReference1.PrestamoResponse Prestamo(Practica1.ServiceReference1.PrestamoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento carnet del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/PrestamoC", ReplyAction="*")]
        Practica1.ServiceReference1.PrestamoCResponse PrestamoC(Practica1.ServiceReference1.PrestamoCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDMask del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/BuscarPedido", ReplyAction="*")]
        Practica1.ServiceReference1.BuscarPedidoResponse BuscarPedido(Practica1.ServiceReference1.BuscarPedidoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codlibro del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/UptadtePrestamo", ReplyAction="*")]
        Practica1.ServiceReference1.UptadtePrestamoResponse UptadtePrestamo(Practica1.ServiceReference1.UptadtePrestamoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registrar", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.RegistrarRequestBody Body;
        
        public RegistrarRequest() {
        }
        
        public RegistrarRequest(Practica1.ServiceReference1.RegistrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class RegistrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tabla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Campos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Valores;
        
        public RegistrarRequestBody() {
        }
        
        public RegistrarRequestBody(string Tabla, string Campos, string Valores) {
            this.Tabla = Tabla;
            this.Campos = Campos;
            this.Valores = Valores;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.RegistrarResponseBody Body;
        
        public RegistrarResponse() {
        }
        
        public RegistrarResponse(Practica1.ServiceReference1.RegistrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class RegistrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrarResult;
        
        public RegistrarResponseBody() {
        }
        
        public RegistrarResponseBody(bool RegistrarResult) {
            this.RegistrarResult = RegistrarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarLibro", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarLibroRequestBody Body;
        
        public BuscarLibroRequest() {
        }
        
        public BuscarLibroRequest(Practica1.ServiceReference1.BuscarLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDMask;
        
        public BuscarLibroRequestBody() {
        }
        
        public BuscarLibroRequestBody(string IDMask) {
            this.IDMask = IDMask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarLibroResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarLibroResponseBody Body;
        
        public BuscarLibroResponse() {
        }
        
        public BuscarLibroResponse(Practica1.ServiceReference1.BuscarLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet BuscarLibroResult;
        
        public BuscarLibroResponseBody() {
        }
        
        public BuscarLibroResponseBody(System.Data.DataSet BuscarLibroResult) {
            this.BuscarLibroResult = BuscarLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarLibroautorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarLibroautor", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarLibroautorRequestBody Body;
        
        public BuscarLibroautorRequest() {
        }
        
        public BuscarLibroautorRequest(Practica1.ServiceReference1.BuscarLibroautorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarLibroautorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDMask;
        
        public BuscarLibroautorRequestBody() {
        }
        
        public BuscarLibroautorRequestBody(string IDMask) {
            this.IDMask = IDMask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarLibroautorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarLibroautorResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarLibroautorResponseBody Body;
        
        public BuscarLibroautorResponse() {
        }
        
        public BuscarLibroautorResponse(Practica1.ServiceReference1.BuscarLibroautorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarLibroautorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet BuscarLibroautorResult;
        
        public BuscarLibroautorResponseBody() {
        }
        
        public BuscarLibroautorResponseBody(System.Data.DataSet BuscarLibroautorResult) {
            this.BuscarLibroautorResult = BuscarLibroautorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechahoyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fechahoy", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.FechahoyRequestBody Body;
        
        public FechahoyRequest() {
        }
        
        public FechahoyRequest(Practica1.ServiceReference1.FechahoyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FechahoyRequestBody {
        
        public FechahoyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechahoyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FechahoyResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.FechahoyResponseBody Body;
        
        public FechahoyResponse() {
        }
        
        public FechahoyResponse(Practica1.ServiceReference1.FechahoyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class FechahoyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FechahoyResult;
        
        public FechahoyResponseBody() {
        }
        
        public FechahoyResponseBody(string FechahoyResult) {
            this.FechahoyResult = FechahoyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ordenarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ordenar", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.ordenarRequestBody Body;
        
        public ordenarRequest() {
        }
        
        public ordenarRequest(Practica1.ServiceReference1.ordenarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ordenarRequestBody {
        
        public ordenarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ordenarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ordenarResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.ordenarResponseBody Body;
        
        public ordenarResponse() {
        }
        
        public ordenarResponse(Practica1.ServiceReference1.ordenarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class ordenarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet ordenarResult;
        
        public ordenarResponseBody() {
        }
        
        public ordenarResponseBody(System.Data.DataSet ordenarResult) {
            this.ordenarResult = ordenarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Prestamo", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.PrestamoRequestBody Body;
        
        public PrestamoRequest() {
        }
        
        public PrestamoRequest(Practica1.ServiceReference1.PrestamoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class PrestamoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Disponible;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Prestado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codlibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int TopPrestamo;
        
        public PrestamoRequestBody() {
        }
        
        public PrestamoRequestBody(int Disponible, int Prestado, string codlibro, int TopPrestamo) {
            this.Disponible = Disponible;
            this.Prestado = Prestado;
            this.codlibro = codlibro;
            this.TopPrestamo = TopPrestamo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrestamoResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.PrestamoResponseBody Body;
        
        public PrestamoResponse() {
        }
        
        public PrestamoResponse(Practica1.ServiceReference1.PrestamoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class PrestamoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PrestamoResult;
        
        public PrestamoResponseBody() {
        }
        
        public PrestamoResponseBody(bool PrestamoResult) {
            this.PrestamoResult = PrestamoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrestamoCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrestamoC", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.PrestamoCRequestBody Body;
        
        public PrestamoCRequest() {
        }
        
        public PrestamoCRequest(Practica1.ServiceReference1.PrestamoCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class PrestamoCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string carnet;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PrestamoCliente;
        
        public PrestamoCRequestBody() {
        }
        
        public PrestamoCRequestBody(string carnet, int PrestamoCliente) {
            this.carnet = carnet;
            this.PrestamoCliente = PrestamoCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrestamoCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrestamoCResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.PrestamoCResponseBody Body;
        
        public PrestamoCResponse() {
        }
        
        public PrestamoCResponse(Practica1.ServiceReference1.PrestamoCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class PrestamoCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PrestamoCResult;
        
        public PrestamoCResponseBody() {
        }
        
        public PrestamoCResponseBody(bool PrestamoCResult) {
            this.PrestamoCResult = PrestamoCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPedido", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarPedidoRequestBody Body;
        
        public BuscarPedidoRequest() {
        }
        
        public BuscarPedidoRequest(Practica1.ServiceReference1.BuscarPedidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarPedidoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDMask;
        
        public BuscarPedidoRequestBody() {
        }
        
        public BuscarPedidoRequestBody(string IDMask) {
            this.IDMask = IDMask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPedidoResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarPedidoResponseBody Body;
        
        public BuscarPedidoResponse() {
        }
        
        public BuscarPedidoResponse(Practica1.ServiceReference1.BuscarPedidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarPedidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet BuscarPedidoResult;
        
        public BuscarPedidoResponseBody() {
        }
        
        public BuscarPedidoResponseBody(System.Data.DataSet BuscarPedidoResult) {
            this.BuscarPedidoResult = BuscarPedidoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UptadtePrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UptadtePrestamo", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.UptadtePrestamoRequestBody Body;
        
        public UptadtePrestamoRequest() {
        }
        
        public UptadtePrestamoRequest(Practica1.ServiceReference1.UptadtePrestamoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class UptadtePrestamoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Prestado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codlibro;
        
        public UptadtePrestamoRequestBody() {
        }
        
        public UptadtePrestamoRequestBody(int Prestado, string codlibro) {
            this.Prestado = Prestado;
            this.codlibro = codlibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UptadtePrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UptadtePrestamoResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.UptadtePrestamoResponseBody Body;
        
        public UptadtePrestamoResponse() {
        }
        
        public UptadtePrestamoResponse(Practica1.ServiceReference1.UptadtePrestamoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class UptadtePrestamoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UptadtePrestamoResult;
        
        public UptadtePrestamoResponseBody() {
        }
        
        public UptadtePrestamoResponseBody(bool UptadtePrestamoResult) {
            this.UptadtePrestamoResult = UptadtePrestamoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Practica1.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Practica1.ServiceReference1.ServiceSoap>, Practica1.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool conectarServidor() {
            return base.Channel.conectarServidor();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.RegistrarResponse Practica1.ServiceReference1.ServiceSoap.Registrar(Practica1.ServiceReference1.RegistrarRequest request) {
            return base.Channel.Registrar(request);
        }
        
        public bool Registrar(string Tabla, string Campos, string Valores) {
            Practica1.ServiceReference1.RegistrarRequest inValue = new Practica1.ServiceReference1.RegistrarRequest();
            inValue.Body = new Practica1.ServiceReference1.RegistrarRequestBody();
            inValue.Body.Tabla = Tabla;
            inValue.Body.Campos = Campos;
            inValue.Body.Valores = Valores;
            Practica1.ServiceReference1.RegistrarResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).Registrar(inValue);
            return retVal.Body.RegistrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.BuscarLibroResponse Practica1.ServiceReference1.ServiceSoap.BuscarLibro(Practica1.ServiceReference1.BuscarLibroRequest request) {
            return base.Channel.BuscarLibro(request);
        }
        
        public System.Data.DataSet BuscarLibro(string IDMask) {
            Practica1.ServiceReference1.BuscarLibroRequest inValue = new Practica1.ServiceReference1.BuscarLibroRequest();
            inValue.Body = new Practica1.ServiceReference1.BuscarLibroRequestBody();
            inValue.Body.IDMask = IDMask;
            Practica1.ServiceReference1.BuscarLibroResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).BuscarLibro(inValue);
            return retVal.Body.BuscarLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.BuscarLibroautorResponse Practica1.ServiceReference1.ServiceSoap.BuscarLibroautor(Practica1.ServiceReference1.BuscarLibroautorRequest request) {
            return base.Channel.BuscarLibroautor(request);
        }
        
        public System.Data.DataSet BuscarLibroautor(string IDMask) {
            Practica1.ServiceReference1.BuscarLibroautorRequest inValue = new Practica1.ServiceReference1.BuscarLibroautorRequest();
            inValue.Body = new Practica1.ServiceReference1.BuscarLibroautorRequestBody();
            inValue.Body.IDMask = IDMask;
            Practica1.ServiceReference1.BuscarLibroautorResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).BuscarLibroautor(inValue);
            return retVal.Body.BuscarLibroautorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.FechahoyResponse Practica1.ServiceReference1.ServiceSoap.Fechahoy(Practica1.ServiceReference1.FechahoyRequest request) {
            return base.Channel.Fechahoy(request);
        }
        
        public string Fechahoy() {
            Practica1.ServiceReference1.FechahoyRequest inValue = new Practica1.ServiceReference1.FechahoyRequest();
            inValue.Body = new Practica1.ServiceReference1.FechahoyRequestBody();
            Practica1.ServiceReference1.FechahoyResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).Fechahoy(inValue);
            return retVal.Body.FechahoyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.ordenarResponse Practica1.ServiceReference1.ServiceSoap.ordenar(Practica1.ServiceReference1.ordenarRequest request) {
            return base.Channel.ordenar(request);
        }
        
        public System.Data.DataSet ordenar() {
            Practica1.ServiceReference1.ordenarRequest inValue = new Practica1.ServiceReference1.ordenarRequest();
            inValue.Body = new Practica1.ServiceReference1.ordenarRequestBody();
            Practica1.ServiceReference1.ordenarResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).ordenar(inValue);
            return retVal.Body.ordenarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.PrestamoResponse Practica1.ServiceReference1.ServiceSoap.Prestamo(Practica1.ServiceReference1.PrestamoRequest request) {
            return base.Channel.Prestamo(request);
        }
        
        public bool Prestamo(int Disponible, int Prestado, string codlibro, int TopPrestamo) {
            Practica1.ServiceReference1.PrestamoRequest inValue = new Practica1.ServiceReference1.PrestamoRequest();
            inValue.Body = new Practica1.ServiceReference1.PrestamoRequestBody();
            inValue.Body.Disponible = Disponible;
            inValue.Body.Prestado = Prestado;
            inValue.Body.codlibro = codlibro;
            inValue.Body.TopPrestamo = TopPrestamo;
            Practica1.ServiceReference1.PrestamoResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).Prestamo(inValue);
            return retVal.Body.PrestamoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.PrestamoCResponse Practica1.ServiceReference1.ServiceSoap.PrestamoC(Practica1.ServiceReference1.PrestamoCRequest request) {
            return base.Channel.PrestamoC(request);
        }
        
        public bool PrestamoC(string carnet, int PrestamoCliente) {
            Practica1.ServiceReference1.PrestamoCRequest inValue = new Practica1.ServiceReference1.PrestamoCRequest();
            inValue.Body = new Practica1.ServiceReference1.PrestamoCRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.PrestamoCliente = PrestamoCliente;
            Practica1.ServiceReference1.PrestamoCResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).PrestamoC(inValue);
            return retVal.Body.PrestamoCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.BuscarPedidoResponse Practica1.ServiceReference1.ServiceSoap.BuscarPedido(Practica1.ServiceReference1.BuscarPedidoRequest request) {
            return base.Channel.BuscarPedido(request);
        }
        
        public System.Data.DataSet BuscarPedido(string IDMask) {
            Practica1.ServiceReference1.BuscarPedidoRequest inValue = new Practica1.ServiceReference1.BuscarPedidoRequest();
            inValue.Body = new Practica1.ServiceReference1.BuscarPedidoRequestBody();
            inValue.Body.IDMask = IDMask;
            Practica1.ServiceReference1.BuscarPedidoResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).BuscarPedido(inValue);
            return retVal.Body.BuscarPedidoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.UptadtePrestamoResponse Practica1.ServiceReference1.ServiceSoap.UptadtePrestamo(Practica1.ServiceReference1.UptadtePrestamoRequest request) {
            return base.Channel.UptadtePrestamo(request);
        }
        
        public bool UptadtePrestamo(int Prestado, string codlibro) {
            Practica1.ServiceReference1.UptadtePrestamoRequest inValue = new Practica1.ServiceReference1.UptadtePrestamoRequest();
            inValue.Body = new Practica1.ServiceReference1.UptadtePrestamoRequestBody();
            inValue.Body.Prestado = Prestado;
            inValue.Body.codlibro = codlibro;
            Practica1.ServiceReference1.UptadtePrestamoResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).UptadtePrestamo(inValue);
            return retVal.Body.UptadtePrestamoResult;
        }
    }
}
