//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:1240/Service.asmx", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/conectarServidor", ReplyAction="*")]
        bool conectarServidor();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Tabla del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/Registrar", ReplyAction="*")]
        Practica1.ServiceReference1.RegistrarResponse Registrar(Practica1.ServiceReference1.RegistrarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDMask del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/BuscarLibro", ReplyAction="*")]
        Practica1.ServiceReference1.BuscarLibroResponse BuscarLibro(Practica1.ServiceReference1.BuscarLibroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDMask del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/BuscarLibroautor", ReplyAction="*")]
        Practica1.ServiceReference1.BuscarLibroautorResponse BuscarLibroautor(Practica1.ServiceReference1.BuscarLibroautorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FechahoyResult del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/Fechahoy", ReplyAction="*")]
        Practica1.ServiceReference1.FechahoyResponse Fechahoy(Practica1.ServiceReference1.FechahoyRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ordenarResult del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/ordenar", ReplyAction="*")]
        Practica1.ServiceReference1.ordenarResponse ordenar(Practica1.ServiceReference1.ordenarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NombreLibro del espacio de nombres http://localhost:1240/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:1240/Service.asmx/Update", ReplyAction="*")]
        Practica1.ServiceReference1.UpdateResponse Update(Practica1.ServiceReference1.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registrar", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.RegistrarRequestBody Body;
        
        public RegistrarRequest() {
        }
        
        public RegistrarRequest(Practica1.ServiceReference1.RegistrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class RegistrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tabla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Campos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Valores;
        
        public RegistrarRequestBody() {
        }
        
        public RegistrarRequestBody(string Tabla, string Campos, string Valores) {
            this.Tabla = Tabla;
            this.Campos = Campos;
            this.Valores = Valores;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.RegistrarResponseBody Body;
        
        public RegistrarResponse() {
        }
        
        public RegistrarResponse(Practica1.ServiceReference1.RegistrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class RegistrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrarResult;
        
        public RegistrarResponseBody() {
        }
        
        public RegistrarResponseBody(bool RegistrarResult) {
            this.RegistrarResult = RegistrarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarLibro", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarLibroRequestBody Body;
        
        public BuscarLibroRequest() {
        }
        
        public BuscarLibroRequest(Practica1.ServiceReference1.BuscarLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDMask;
        
        public BuscarLibroRequestBody() {
        }
        
        public BuscarLibroRequestBody(string IDMask) {
            this.IDMask = IDMask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarLibroResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarLibroResponseBody Body;
        
        public BuscarLibroResponse() {
        }
        
        public BuscarLibroResponse(Practica1.ServiceReference1.BuscarLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet BuscarLibroResult;
        
        public BuscarLibroResponseBody() {
        }
        
        public BuscarLibroResponseBody(System.Data.DataSet BuscarLibroResult) {
            this.BuscarLibroResult = BuscarLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarLibroautorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarLibroautor", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarLibroautorRequestBody Body;
        
        public BuscarLibroautorRequest() {
        }
        
        public BuscarLibroautorRequest(Practica1.ServiceReference1.BuscarLibroautorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarLibroautorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDMask;
        
        public BuscarLibroautorRequestBody() {
        }
        
        public BuscarLibroautorRequestBody(string IDMask) {
            this.IDMask = IDMask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarLibroautorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarLibroautorResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.BuscarLibroautorResponseBody Body;
        
        public BuscarLibroautorResponse() {
        }
        
        public BuscarLibroautorResponse(Practica1.ServiceReference1.BuscarLibroautorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class BuscarLibroautorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet BuscarLibroautorResult;
        
        public BuscarLibroautorResponseBody() {
        }
        
        public BuscarLibroautorResponseBody(System.Data.DataSet BuscarLibroautorResult) {
            this.BuscarLibroautorResult = BuscarLibroautorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechahoyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fechahoy", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.FechahoyRequestBody Body;
        
        public FechahoyRequest() {
        }
        
        public FechahoyRequest(Practica1.ServiceReference1.FechahoyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FechahoyRequestBody {
        
        public FechahoyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechahoyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FechahoyResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.FechahoyResponseBody Body;
        
        public FechahoyResponse() {
        }
        
        public FechahoyResponse(Practica1.ServiceReference1.FechahoyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class FechahoyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FechahoyResult;
        
        public FechahoyResponseBody() {
        }
        
        public FechahoyResponseBody(string FechahoyResult) {
            this.FechahoyResult = FechahoyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ordenarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ordenar", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.ordenarRequestBody Body;
        
        public ordenarRequest() {
        }
        
        public ordenarRequest(Practica1.ServiceReference1.ordenarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ordenarRequestBody {
        
        public ordenarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ordenarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ordenarResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.ordenarResponseBody Body;
        
        public ordenarResponse() {
        }
        
        public ordenarResponse(Practica1.ServiceReference1.ordenarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class ordenarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet ordenarResult;
        
        public ordenarResponseBody() {
        }
        
        public ordenarResponseBody(System.Data.DataSet ordenarResult) {
            this.ordenarResult = ordenarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Practica1.ServiceReference1.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int prestamolibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NombreLibro;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(int prestamolibro, string NombreLibro) {
            this.prestamolibro = prestamolibro;
            this.NombreLibro = NombreLibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://localhost:1240/Service.asmx", Order=0)]
        public Practica1.ServiceReference1.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Practica1.ServiceReference1.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:1240/Service.asmx")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(System.Data.DataSet UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Practica1.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Practica1.ServiceReference1.ServiceSoap>, Practica1.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool conectarServidor() {
            return base.Channel.conectarServidor();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.RegistrarResponse Practica1.ServiceReference1.ServiceSoap.Registrar(Practica1.ServiceReference1.RegistrarRequest request) {
            return base.Channel.Registrar(request);
        }
        
        public bool Registrar(string Tabla, string Campos, string Valores) {
            Practica1.ServiceReference1.RegistrarRequest inValue = new Practica1.ServiceReference1.RegistrarRequest();
            inValue.Body = new Practica1.ServiceReference1.RegistrarRequestBody();
            inValue.Body.Tabla = Tabla;
            inValue.Body.Campos = Campos;
            inValue.Body.Valores = Valores;
            Practica1.ServiceReference1.RegistrarResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).Registrar(inValue);
            return retVal.Body.RegistrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.BuscarLibroResponse Practica1.ServiceReference1.ServiceSoap.BuscarLibro(Practica1.ServiceReference1.BuscarLibroRequest request) {
            return base.Channel.BuscarLibro(request);
        }
        
        public System.Data.DataSet BuscarLibro(string IDMask) {
            Practica1.ServiceReference1.BuscarLibroRequest inValue = new Practica1.ServiceReference1.BuscarLibroRequest();
            inValue.Body = new Practica1.ServiceReference1.BuscarLibroRequestBody();
            inValue.Body.IDMask = IDMask;
            Practica1.ServiceReference1.BuscarLibroResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).BuscarLibro(inValue);
            return retVal.Body.BuscarLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.BuscarLibroautorResponse Practica1.ServiceReference1.ServiceSoap.BuscarLibroautor(Practica1.ServiceReference1.BuscarLibroautorRequest request) {
            return base.Channel.BuscarLibroautor(request);
        }
        
        public System.Data.DataSet BuscarLibroautor(string IDMask) {
            Practica1.ServiceReference1.BuscarLibroautorRequest inValue = new Practica1.ServiceReference1.BuscarLibroautorRequest();
            inValue.Body = new Practica1.ServiceReference1.BuscarLibroautorRequestBody();
            inValue.Body.IDMask = IDMask;
            Practica1.ServiceReference1.BuscarLibroautorResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).BuscarLibroautor(inValue);
            return retVal.Body.BuscarLibroautorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.FechahoyResponse Practica1.ServiceReference1.ServiceSoap.Fechahoy(Practica1.ServiceReference1.FechahoyRequest request) {
            return base.Channel.Fechahoy(request);
        }
        
        public string Fechahoy() {
            Practica1.ServiceReference1.FechahoyRequest inValue = new Practica1.ServiceReference1.FechahoyRequest();
            inValue.Body = new Practica1.ServiceReference1.FechahoyRequestBody();
            Practica1.ServiceReference1.FechahoyResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).Fechahoy(inValue);
            return retVal.Body.FechahoyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.ordenarResponse Practica1.ServiceReference1.ServiceSoap.ordenar(Practica1.ServiceReference1.ordenarRequest request) {
            return base.Channel.ordenar(request);
        }
        
        public System.Data.DataSet ordenar() {
            Practica1.ServiceReference1.ordenarRequest inValue = new Practica1.ServiceReference1.ordenarRequest();
            inValue.Body = new Practica1.ServiceReference1.ordenarRequestBody();
            Practica1.ServiceReference1.ordenarResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).ordenar(inValue);
            return retVal.Body.ordenarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica1.ServiceReference1.UpdateResponse Practica1.ServiceReference1.ServiceSoap.Update(Practica1.ServiceReference1.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public System.Data.DataSet Update(int prestamolibro, string NombreLibro) {
            Practica1.ServiceReference1.UpdateRequest inValue = new Practica1.ServiceReference1.UpdateRequest();
            inValue.Body = new Practica1.ServiceReference1.UpdateRequestBody();
            inValue.Body.prestamolibro = prestamolibro;
            inValue.Body.NombreLibro = NombreLibro;
            Practica1.ServiceReference1.UpdateResponse retVal = ((Practica1.ServiceReference1.ServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
    }
}
